import { Theme, Resource } from "@/pages/Index";

// Free educational resources
const BookResources: Resource[] = [
  {
    id: "r1",
    title: "Khan Academy",
    description: "Free online courses, lessons and practice",
    url: "https://www.khanacademy.org",
    type: "website",
    genre: "academic",
    rating: 4.8,
  },
  {
    id: "r2",
    title: "Coursera Free Courses",
    description: "Access thousands of free courses from top universities",
    url: "https://www.coursera.org/courses?query=free",
    type: "website",
    genre: "academic",
    rating: 4.7,
  },
  {
    id: "r3",
    title: "Scratch Programming",
    description: "Learn to code with visual programming blocks",
    url: "https://scratch.mit.edu",
    type: "interactive",
    genre: "kids",
    rating: 4.9,
  },
  {
    id: "r4",
    title: "Academic Earth",
    description: "Free video lectures from top universities",
    url: "https://academicearth.org/",
    type: "video",
    genre: "academic",
    rating: 4.6,
  },
  {
    id: "r5",
    title: "MIT OpenCourseWare",
    description: "Free lecture notes, exams, and videos from MIT",
    url: "https://ocw.mit.edu",
    type: "website",
    genre: "academic",
    rating: 4.8,
  },
  {
    id: "r6",
    title: "Duolingo",
    description: "Learn languages for free with game-like lessons",
    url: "https://www.duolingo.com",
    type: "interactive",
    genre: "academic",
    rating: 4.5,
  },
  {
    id: "r7",
    title: "PBS Kids",
    description: "Educational games and videos featuring popular characters.",
    url: "https://pbskids.org/",
    type: "interactive",
    genre: "kids",
    rating: 4.8,
  },
  {
    id: "r8",
    title: "Starfall",
    description: "Phonics-based reading activities and math games.",
    url: "https://starfall.com",
    type: "interactive",
    genre: "kids",
    rating: 4.8,
  },
  {
    id: "r9",
    title: "Sesame Streets",
    description:
      "Promotes emotional learning and basic academics by Videos, games, and art tools featuring Sesame Street characters.",
    url: "https://www.sesamestreet.org/",
    type: "interactive",
    genre: "kids",
    rating: 4.8,
  },
  {
    id: "r10",
    title: "National Geographic Kids",
    description:
      "Fun facts, videos, and games about animals, nature, and science.",
    url: "https://kids.nationalgeographic.com/",
    type: "video",
    genre: "kids",
    rating: 4.8,
  },
  {
    id: "r11",
    title: "Funbrain",
    description: "Interactive math, reading, and logic games for kids.",
    url: "https://www.funbrain.com/",
    type: "interactive",
    genre: "kids",
    rating: 4.8,
  },
  {
    id: "r12",
    title: "Coolmath Games",
    description: "Fun math games and puzzles for kids.",
    url: "https://www.coolmathgames.com/",
    type: "interactive",
    genre: "kids",
    rating: 4.8,
  },
  {
    id: "r13",
    title: "Tynker",
    description: "Coding courses for ages 5+.",
    url: "https://www.tynker.com/",
    type: "interactive",
    genre: "academic",
    rating: 4.8,
  },
  {
    id: "r14",
    title: "Code.org",
    description: "Free coding courses starting from age 5.",
    url: "https://code.org/",
    type: "interactive",
    genre: "academic",
    rating: 4.8,
  },
  {
    id: "r15",
    title: "Prodigy Math Game",
    description: "Curriculum-aligned math games for kids.",
    url: "https://www.prodigygame.com/",
    type: "interactive",
    genre: "kids",
    rating: 4.8,
  },
  {
    id: "r16",
    title: "Epic! (Free for educators)",
    description: "Digital library with 40,000+ books for kids 12 and under.",
    url: "https://www.getepic.com/",
    type: "interactive",
    genre: "academic",
    rating: 4.8,
  },
  {
    id: "r17",
    title: "Storyline Online",
    description: "Celebrities read children’s books aloud.",
    url: "https://www.storylineonline.net/",
    type: "video",
    genre: "academic",
    rating: 4.8,
  },
  {
    id: "r18",
    title: "Project Gutenberg",
    description:
      "Over 70,000 free eBooks including classics and public domain works",
    url: "https://www.gutenberg.org",
    type: "free books",
    genre: "library",
    rating: 4.9,
  },
  {
    id: "r19",
    title: "Open Library",
    description: "Internet Archive's open library with millions of free books",
    url: "https://openlibrary.org",
    type: "free books",
    genre: "library",
    rating: 4.8,
  },
  {
    id: "r20",
    title: "ManyBooks",
    description: "Free eBooks in multiple formats with great categorization",
    url: "https://manybooks.net",
    type: "free books",
    genre: "library",
    rating: 4.7,
  },
  {
    id: "r21",
    title: "Free-eBooks.net",
    description: "Large collection of free eBooks across all genres",
    url: "https://www.free-ebooks.net",
    type: "free books",
    genre: "library",
    rating: 4.6,
  },
  {
    id: "r22",
    title: "Feedbooks",
    description: "Public domain books and original works by new authors",
    url: "https://www.feedbooks.com/publicdomain",
    type: "free books",
    genre: "library",
    rating: 4.5,
  },
  {
    id: "r23",
    title: "BookBoon",
    description: "Free textbooks for students - business, engineering, IT",
    url: "https://bookboon.com",
    type: "free books",
    genre: "library",
    rating: 4.7,
  },
  {
    id: "r24",
    title: "Internet Archive Books",
    description: "Massive digital library with books, movies, music, and more",
    url: "https://archive.org/details/books",
    type: "free books",
    genre: "library",
    rating: 4.8,
  },
  {
    id: "r25",
    title: "Smashwords",
    description: "Independent authors and publishers - many free books",
    url: "https://www.smashwords.com/books/category/1/newest/0/free/any",
    type: "free books",
    genre: "library",
    rating: 4.4,
  },
  {
    id: "r26",
    title: "Google Books",
    description: "Many free books and previews from Google's vast collection",
    url: "https://books.google.com",
    type: "free books",
    genre: "library",
    rating: 4.6,
  },
  {
    id: "r27",
    title: "Loyal Books",
    description: "Free audiobooks and eBooks of classic literature",
    url: "https://loyalbooks.com",
    type: "free books",
    genre: "library",
    rating: 4.5,
  },
  {
    id: "r28",
    title: "Planet eBook",
    description: "Classic literature with beautiful PDF formatting",
    url: "https://www.planetebook.com",
    type: "free books",
    genre: "library",
    rating: 4.7,
  },
  {
    id: "r29",
    title: "Standard Ebooks",
    description: "High-quality, carefully formatted public domain books",
    url: "https://standardebooks.org",
    type: "free books",
    genre: "library",
    rating: 4.8,
  },
  {
    id: "r30",
    title: "Children's Books Online",
    description: "Free illustrated children's books and stories",
    url: "https://www.childrensbooksonline.org",
    type: "free books",
    genre: "library",
    rating: 4.6,
  },
  {
    id: "r31",
    title: "International Children's Digital Library",
    description: "Children's books from around the world in multiple languages",
    url: "http://en.childrenslibrary.org",
    type: "free books",
    genre: "library",
    rating: 4.7,
  },
  {
    id: "r32",
    title: "MIT Press Direct",
    description: "Free academic books and journals from MIT Press",
    url: "https://direct.mit.edu",
    type: "free books",
    genre: "library",
    rating: 4.8,
  },
  {
    id: "r33",
    title: "OAPEN Library",
    description: "Open access academic books across various disciplines",
    url: "https://oapen.org",
    type: "free books",
    genre: "library",
    rating: 4.7,
  },
  {
    id: "r34",
    title: "Wikibooks",
    description: "Collaborative textbooks and educational resources",
    url: "https://en.wikibooks.org",
    type: "free books",
    genre: "library",
    rating: 4.5,
  },
  {
    id: "r35",
    title: "HathiTrust Digital Library",
    description: "Millions of books from academic and research libraries",
    url: "https://www.hathitrust.org",
    type: "free books",
    genre: "library",
    rating: 4.6,
  },
  {
    id: "r36",
    title: "Grammarly Handbook",
    description: "Grammar rules, writing tips, and examples",
    url: "https://www.grammarly.com/blog/category/handbook/",
    type: "website",
    genre: "academic",
    rating: 4.6,
  },
  {
    id: "r37",
    title: "CrashCourse",
    description:
      "Engaging video series on World History, US History, Government, and more",
    url: "https://www.youtube.com/user/crashcourse",
    type: "video",
    genre: "academic",
    rating: 4.6,
  },
  {
    id: "r38",
    title: "Library of Congress - Learning",
    description:
      "Primary sources and educational resources for history and civics",
    url: "https://www.loc.gov/education/",
    type: "website",
    genre: "academic",
    rating: 4.6,
  },
];

export default BookResources;
